### ISSUE TITLE
Resolve foreign-key columns the laravel-5.4-way for model relations

### ISSUE THREAD

**Issue by JJWesterkamp** [czim/laravel-cms-models#20]
Starting with Laravel 5.4, foreign key fields for Eloquent relations are resolved by the related model's _primary key name_ and _table name_. According to the [Laravel upgrade guide](https://laravel.com/docs/5.4/upgrade):

> If the foreign key is not explicitly specified when defining a relationship, Eloquent will now use the table name and primary key name for the related model to build the foreign key. For the vast majority of applications, this is not a change of behavior.

For example:

```php
/**
 * @property int $id - The primary key of Project
 */
class Project extends Model
{
    // this model's table name would be 'projects', so any foreign key would be
    //  built as 'project_id' by default, starting from Laravel 5.4
}
```
This means that I should be able to name my relation methods anything I see fit to provide some semantics, such as in the example below, where the relation method points to a certain `Employee`'s _favorite_ `Project`:

```php
// Some other model that 'belongsTo' project...

class Employee extends Model
{
    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function favoriteProject()
    {
        return $this->belongsTo(Project::class);
    }
}
```

Within Laravel itself everything works as expected, but when I try to load the above model in the CMS, I get the following error:

```
Issue analysing model App\Models\Employee: 
Foreign key ‘favorite_project_id’ defined for relation does not exist on model App\Models\Employee
```

**Am I missing some configuration step?** The workaround I have for now is just explicitly specifying the foreign key name in the `belongsTo` call, but I'd prefer to be able to omit that second argument: 
```
return $this->belongsTo(Project::class, 'project_id');
```

Relevant info from my `composer.json` file:

```json
{
    "require": {
        "czim/laravel-cms-acl-module": "0.9.3",
        "czim/laravel-cms-auth": "1.4.2",
        "czim/laravel-cms-core": "1.4.6",
        "czim/laravel-cms-models": "1.4.4",
        "czim/laravel-cms-theme": "0.9.8",
        "czim/laravel-cms-upload-module": "1.0.2",
    }
}
```

**Comment by czim** [comment]
Thanks for the elaborate issue report!
This strikes me as weird though, since the CMS analyzer retrieves the foreign keys from the Eloquent relation instance. It does not use its 'own' logic for determining keys.

I'll see if I can reproduce this.

**Comment by czim** [comment]
As far as I can tell, Laravel 5.4 does *not* generate foreign keys this way.
It seems to me that the Laravel documentation is actually incorrect on this score:

https://github.com/illuminate/database/blob/5.4/Eloquent/Concerns/HasRelationships.php#L112

This shows that the name is still determined by the method name (`$relation`).
