### ISSUE TITLE
The form display strategy alias for password should force the type to password by default

### ISSUE THREAD

**Issue by Piet-Hein** [czim/laravel-cms-models#38]
When using the enum value `\Czim\CmsModels\Support\Enums\FormDisplayStrategy::PASSWORD` for a form display strategy, this refers to the DefaultStrategy, but without setting the type. Unless `options.type` is set to `password`, this causes unexpected behavior (a normal text input, instead of a password field).

**Comment by czim** [comment]
Addressed in version 1.6.1 (and equivalents for older Laravel versions).
